version: '3.8'
services:
    api:
        container_name: news_aggregator_api
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        depends_on:
            mysql:
                condition: service_healthy

    scheduler:
        container_name: news_aggregator_scheduler
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
        environment:
            ROLE: scheduler
        depends_on:
            api:
                condition: service_started
            mysql:
                condition: service_healthy

    mysql:
        container_name: news_aggregator_mysql
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_ROOT_HOST: ${DB_HOST}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db-data:/var/lib/mysql
        ports:
            - "3306:3306"
        healthcheck:
            test: [ "CMD", "mysqladmin" ,"ping", "-p${DB_PASSWORD}" ]
            retries: 3
            timeout: 5s
volumes:
    db-data:
        driver: local
